# Generated by Django 4.2.3 on 2023-10-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Controller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ki", models.FloatField()),
                ("kp", models.FloatField()),
                ("setPoint", models.FloatField()),
            ],
        ),
    ]
