# Generated by Django 4.2.3 on 2023-10-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ContentPage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("body", models.CharField(max_length=255)),
                ("fontAwesome", models.CharField(max_length=50)),
            ],
        ),
    ]
