# Generated by Django 4.2.3 on 2023-10-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EndPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ipAddress", models.CharField(max_length=15)),
                ("port", models.CharField(max_length=4)),
            ],
        ),
    ]
